name: Build aks-desktop (Windows)

on:
  schedule:
    # Runs every day at 1:00 AM UTC
    - cron: '0 1 * * *'
  workflow_dispatch:
    inputs:
      aks_plugin_branch:
        description: 'Branch to build aks-plugin'
        required: true
        default: 'main'

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Install golang
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version: '1.24.*'

      - name: Setup nodejs
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: 20.x

      - name: Checkout this repository with submodules
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          ref: ${{ github.event.inputs.aks_plugin_branch }}
          submodules: recursive

      - name: Setup AKS desktop and Build Headlamp (Windows)
        run: npm run build:win-ci
        shell: bash

      - name: Upload Windows build artifact
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: aks-desktop-win
          path: headlamp/app/dist/aks-desktop*.*
